version: '3'

services:
 vote:
  image: dockersamples/examplevotingapp_vote:before
  ports:
   - 5000:80
  networks:
   - Frontend

 redis:
  image: redis:3.2
  networks:
   - Frontend
  
 worker:
  image: dockersamples/examplevotingapp_worker
  networks:
   - Frontend
   - Backend

 db:
  image: postgres:12.4
  environment:
   POSTGRES_HOST_AUTH_METHOD: trust
   POSTGRES_USER: test_user
   POSTGRES_PASSWORD: password
   POSTGRES_DB: test_db
  volumes:
   - db-data:/var/lib/postgresql/data
  networks:
   - Backend
  
 result:
  image: dockersamples/examplevotingapp_result:before
  ports:
   - 5001:80
  networks:
   - Backend
networks:
 Frontend:
  driver: bridge
 Backend:
  driver: bridge

volumes:
  db-data: